### ISSUE TITLE
Configure push/pull requests to trigger CI/CD.

### ISSUE THREAD

**Issue by williamowen65** [williamowen65/atlas-the-public-think-tank#28]

**Comment by williamowen65** [comment]
```yml
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:       # Trigger on any push to any branch
    branches: ["*"]  # Wildcard to match any branch
  pull_request:  # Trigger on any pull request to any branch
    branches: ["*"]  # Wildcard to match any branch

jobs:
  Run-CloudTests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName~CloudTests
```
